core/blog/api/v1/urls.py
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from .views import PostList, PostDetail, PostModelViewSet, CategoryModelViewSet
from rest_framework.routers import DefaultRouter, SimpleRouter

router = DefaultRouter()
router.register("post", PostModelViewSet, basename="post")
router.register("category", CategoryModelViewSet, basename="category")

app_name = "api-v1"

urlpatterns = router.urls


# urlpatterns = [
#     path("post/",PostViewSet.as_view({'get':'list','post':'create'}),name='post-list'),
#     path("post/<int:pk>/",PostViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update','delete':'destroy'}),name='post-detail')
#     # path('post/',PostList.as_view(),name = "post-list"),
#     # path('post/<int:id>/',PostDetail.as_view(),name = "post-list"),
# ]

core/blog/urls.py
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from .views import (
    IndexView,
    PostEdit,
    PostDelete,
    PostCreate,
    RedirectToMaktab,
    PostList,
    PostDetail,
    PostListAPI,
)


app_name = "blog"

urlpatterns = [
    # path('fbv-index', indexView, name= "fbv-test"),
    path("", IndexView.as_view(), name="index"),
    # path('cbv-index', TemplateView.as_view(template_name="index.html")),
    path("cbv-index", IndexView.as_view(), name="cbv-index"),
    # path('go-to-index/', RedirectView.as_view(pattern_name = "blog:cbv-index" ), name='go-to-maktabkhooneh'),
    # path('go-to-maktabkhooneh/<int:pk>', RedirectToMaktab.as_view(),name="go-to-maktab"),
    path("post/api/", PostListAPI.as_view(), name="post-list-api"),
    path("post/", PostList.as_view(), name="post-list"),
    path("post/<int:pk>/", PostDetail.as_view(), name="post-detail"),
    path("post/create/", PostCreate.as_view(), name="post-create"),
    path("post/<int:pk>/edit/", PostEdit.as_view(), name="post-edit"),
    path("post/<int:pk>/delete/", PostDelete.as_view(), name="post-delete"),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="Novini.n1380@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path(
        "swagger/output.json/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api-docs/", include_docs_urls(title="api sample")),
]


# serving static and media for dev mode
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from accounts.models import Profile
from django.urls import reverse

# Create your models here.

# getting user model object
User = get_user_model()


class Post(models.Model):
    """
    this is a class to define posts for blog app
    """

    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    status = models.BooleanField()
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.content[:5]

    def get_api_absolute_url(self):
        return reverse("blog:api-v1:post-detail", kwargs={"pk": self.pk})


class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from .models import Post


class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "status", "category", "published_date"]

core/blog/api/v1/views.py
from rest_framework.decorators import api_view, action, permission_classes
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from .serializers import PostSerializer, CategorySerializer
from ...models import Post, Category
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView  # for classbased views
from rest_framework.generics import (
    GenericAPIView,
    ListAPIView,
    ListCreateAPIView,
    RetrieveAPIView,
    RetrieveUpdateDestroyAPIView,
)
from rest_framework import mixins, viewsets
from .permissions import IsOwnerOrReadOnly
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from .paginations import LargeResultsSetPagination, DefaultPagination
from .filters import PostFilters


class PostList(
    ListCreateAPIView
):  # GenericAPIView,mixins.ListModelMixin, mixins.CreateModelMixin
    """Getting a list of post and creating new post by class based views"""

    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    serializer_class = PostSerializer  # for form in api view
    queryset = Post.objects.filter(status=True)
    filter_backends = [DjangoFilterBackend]

    '''def get(self,request,*args , **kwargs):
        """ read and getting data """
        # queryset = self.get_queryset()
        # serializer = self.serializer_class(queryset,many=True)
        return self.list(request,*args , **kwargs)
    
    
    def post(self,request,*args , **kwargs):
        return self.create(request,*args , **kwargs)'''


class PostDetail(
    RetrieveUpdateDestroyAPIView
):  # GenericAPIView,mixins.RetrieveModelMixin,mixins.UpdateModelMixin,mixins.DestroyModelMixin
    """Getting a list of post and creating new post by class based views"""

    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)
    lookup_field = "id"  # mishe tu urls.py ham 'pk' dad behesh


"""    def get(self,request,*args,**kwargs):
        return self.retrieve(request,*args,**kwargs)
    
    def put(self,request,*args,**kwargs):
        return self.update(request,*args,**kwargs)
    
    def delete(self,request,*args,**kwargs):
        return self.destroy(request,*args,**kwargs)"""


# example of viewset in class based view
class PostModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    # filterset_fields = ['category','author','status']    #Normal
    filterset_fields = {
        "category": ["exact", "in"],
        "author": ["exact"],
        "status": ["exact"],
    }  # view filtering
    # filterset_fields = PostFilters   #based on filters.py filtering(it like up but it defines in different classes)
    search_fields = ["title", "content"]
    ordering_fields = ["published_date"]
    pagination_class = DefaultPagination

    @action(methods=["get"], detail=False)
    def get_ok(self, request):
        return Response({"detail": "OK"})

    # def list(self,request):
    #     serializer = self.serializer_class(self.queryset,many=True)
    #     return Response(serializer.data)

    # def retrieve(self,request,pk=None):
    #     post_object = get_object_or_404(self.queryset,pk=pk)
    #     serializer = self.serializer_class(post_object)
    #     return Response(serializer.data)

    # def create(self,request):
    #     pass

    # def update(self, request, pk=None):
    #     pass

    # def partial_update(self, request, pk=None):
    #     pass

    # def destroy(self, request, pk=None):
    #     pass


class CategoryModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = CategorySerializer
    queryset = Category.objects.all()


'''class PostList(APIView):
    """ Getting a list of post and creating new post by class based views"""
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer  #for form in api view
    def get(self,request):
        """ read and getting data """
        posts = Post.objects.all()
        serializer = PostSerializer(posts,many=True)
        return Response(serializer.data)
    def post(self,request):
        """ Creating post with provided data"""
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)'''


'''class PostDetail(APIView):
    """ Getting detail of post and edit or delete it"""
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer
    def get(self,request,id):
        """ retrieving the post data """
        post = get_object_or_404(Post,pk=id,status=True)
        serializer = self.serializer_class(post)
        return Response(serializer.data)
    def put(self,request,id):
        """ editing the post data """
        post = get_object_or_404(Post,pk=id,status=True)
        serializer = self.serializer_class(post,data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    def delete(self,request,id):
        """ deleting the post data """
        post = get_object_or_404(Post,pk=id,status=True)
        post.delete()
        return Response({"detail":"Item removed successfully"},status=status.HTTP_204_NO_CONTENT)'''


######### function based views for api ############

"""@api_view(["GET","POST"])
@permission_classes([IsAuthenticatedOrReadOnly])
def PostList(request):
    if request.method == "GET":
        posts = Post.objects.all()
        serializer = PostSerializer(posts,many=True)
        return Response(serializer.data)
    elif request.method == "POST":
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
        # if serializer.is_valid():
        #     serializer.save()
        #     return Response(serializer.data)
        # else:
        #     return Response(serializer.errors)

@api_view(["GET","PUT","DELETE"])
@permission_classes([IsAuthenticatedOrReadOnly])
def PostDetail(request,id):
    # try:
    #     post = Post.objects.get(pk=id)
    #     serializer = PostSerializer(post)
    #     return Response(serializer.data)
    # except Post.DoesNotExist:
    #     return Response({"detail":"Post does not exist"}, status=status.HTTP_404_NOT_FOUND)  #status=404
    post = get_object_or_404(Post,pk=id)
    if request.method == "GET":
        serializer = PostSerializer(post)
        return Response(serializer.data)
    elif request.method == "PUT":
        serializer = PostSerializer(post,data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    elif request.method == "DELETE":
        post.delete()
        return Response({"detail":"Item removed successfully"},status=status.HTTP_204_NO_CONTENT)"""

core/blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import (
    DeleteView,
    UpdateView,
    CreateView,
    FormView,
    ListView,
    TemplateView,
    RedirectView,
    DetailView,
)
from .models import Post, Category
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from .forms import ContactForm, PostForm
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

# Create your views here.

# Create your views here.

# Function Base View show a template
''' 
def indexView(request):
    """
    a function based view to show index page
    """
    name = "ali"
    context = {"name":name}
    return render(request,"index.html",context)
'''


class IndexView(TemplateView):
    """
    a class based view to show index page
    """

    template_name = "index.html"

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context["name"] = "ali"
        context["posts"] = Post.objects.all()
        return context


""" FBV or redirect 

def redirectToMaktab(requset):
    return redirect('https://maktabkhooneh.com')
    
"""


class RedirectToMaktab(RedirectView):
    url = "https://maktabkhooneh.com"

    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs["pk"])
        print(post)
        return super().get_redirect_url(*args, **kwargs)


class PostList(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = Post
    """  type of model definition  """
    # queryset = Post.objects.all()
    # def get_queryset(self):
    #     posts = Post.objects.filter(status = True)
    #     return posts
    context_object_name = "posts"
    paginate_by = 5
    ordering = "-id"
    permission_required = "blog.view_post"


class PostDetail(LoginRequiredMixin, DetailView):
    model = Post


"""    
class PostCreate(FormView):
    template_name = 'contact.html'
    form_class = PostForm
    success_url = '/blog/post/'
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)"""


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    """  this is two ways to identify fields to project  """
    form_class = PostForm
    # fields = ['author','title','content','status','category','published_date']
    success_url = "/blog/post/"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostEdit(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/post/"


class PostDelete(DeleteView):
    model = Post
    success_url = "/blog/post/"



class PostListAPI(TemplateView):
    template_name = 'blog/post_list_api.html'

core/templates/blog/post_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

core/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{post.title}}</h1>
    <hr>
        <small>{{post.author}},,{{post.published_date}}</small>
        <p>{{post.content}}</p>
    </hr>
</body>
</html>

core/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create posts</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">
    </form>
</body>
</html>

core/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ol>
        <h1>Blog Posts</h1>
        {% for post in posts %}
        <li>
        
            <a href="{% url 'blog:post-detail' pk=post.id %}" ><h2>{{post.id}} - {{post.title}}</h2></a>
            <a href="{% url 'blog:post-edit' pk=post.id %}">
                <h5>Edit</h5>
            </a>
            <a href="{% url 'blog:post-delete' pk=post.id %}">
                <h5>Delete</h5>
            </a>
            <small>{{post.author.first_name}} {{post.author.last_name}},, {{post.published_date}}</small>
        
        </li>
        {% endfor %}
    </ol>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>
</html>

core/templates/blog/post_list_api.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ol id="post-wrapper">
        <h1>Blog Posts</h1>

        {% comment %} <li>
        
            <a href="{% url 'blog:post-detail' pk=post.id %}" ><h2>{{post.id}} - {{post.title}}</h2></a>
            <a href="{% url 'blog:post-edit' pk=post.id %}">
                <h5>Edit</h5>
            </a>
            <a href="{% url 'blog:post-delete' pk=post.id %}">
                <h5>Delete</h5>
            </a>
            <small>{{post.author.first_name}} {{post.author.last_name}},, {{post.published_date}}</small>
        
        </li> {% endcomment %}

    </ol>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        
        $.get('/blog/api/v1/post/',  // url
        function (data, textStatus, jqXHR) {  // success callback
            wrapper = $("#post-wrapper");
            for (post of data.results){
                wrapper.append(`<li> <a href="${post.absolute_url}"><h2>${post.title}</h2></a></li>`)
            }

            // alert('status: ' + textStatus + ', data:' + data);
            // console.log(data);

        });
    </script>
</body>
</html>